name: actual
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.6.0


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  flutter_secure_storage: ^9.2.4
  json_annotation: ^4.9.0
  retrofit: ^4.4.0
  logger: ^2.4.0
  flutter_riverpod: ^2.6.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.3.3
  json_serializable: ^6.8.0
  retrofit_generator: '>=8.0.0 <10.0.0'


flutter:

  uses-material-design: true

  fonts:
    - family: NotoSans
      fonts:
        - asset: asset/fonts/NotoSansKR-Black.otf
          weight: 900
        - asset: asset/fonts/NotoSansKR-Bold.otf
          weight: 700
        - asset: asset/fonts/NotoSansKR-Medium.otf
          weight: 500
        - asset: asset/fonts/NotoSansKR-Regular.otf
          weight: 400
        - asset: asset/fonts/NotoSansKR-Light.otf
          weight: 300
        - asset: asset/fonts/NotoSansKR-Thin.otf
          weight: 100


  assets:
    - asset/
    - asset/img/
    - asset/img/food/
    - asset/img/logo/
    - asset/img/misc/
    - asset/svg/
    - asset/svg/icon/
    - asset/rive/
    - asset/fonts/

